# Generated by Django 5.1.6 on 2025-02-08 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tender_number", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("published_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("submitted_documents", models.TextField()),
                ("shortfall_documents", models.TextField(blank=True, null=True)),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenders.tender"
                    ),
                ),
            ],
        ),
    ]
