# Generated by Django 5.1.6 on 2025-02-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_department_tender_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='shortfall_documents',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='submitted_documents',
            field=models.FileField(blank=True, null=True, upload_to='vendor_documents/'),
        ),
    ]
