# Generated by Django 5.1.6 on 2025-02-26 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_remove_vendor_submitted_documents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='shortfallDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='shortfall_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for document shortfall')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortfall_documents', to='tenders.vendor')),
            ],
        ),
    ]
