# Generated by Django 5.1.6 on 2025-02-26 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_shortfalldocuments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shortfallDocuments',
            new_name='ShortfallDocument',
        ),
    ]
