# Generated by Django 5.1.6 on 2025-02-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0007_rename_shortfalldocuments_shortfalldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortfalldocument',
            name='shortfall_stage',
            field=models.IntegerField(choices=[(1, 'Shortfall 1'), (2, 'Shortfall 2'), (3, 'Shortfall 3')], default=1),
        ),
    ]
