# Generated by Django 5.1.6 on 2025-03-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0008_shortfalldocument_shortfall_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortfalldocument',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for document shortfall', null=True),
        ),
    ]
